#!/usr/bin/perl
#=======================
# Author : Ali Moradzade
# Created: 2022/02/03
#=======================
use warnings;
use v5.10;
use utf8;
use autodie;

#ex8 02 word end with a

while (<>) {
	chomp;
	if (/\b\w+a\b/) {
		say "\tMatched: |$`<$&>$'|";
	} else {
		say "\tNo match: |$_|";
	}
}

