#!/usr/bin/perl
#=======================
# Author : Ali Moradzade
# Created: 2022/02/03
#=======================
use warnings;
use v5.10;
use utf8;
use autodie;

#ex8 01 pattern match

while (<>) {
	chomp;
	if (/match/) {
		say "\tMatched: |$`<$&>$'|";
	} else {
		say "\tNo match: |$_|";
	}
}
