#!/usr/bin/perl
#=======================
# Author : Ali Moradzade
# Created: 2022/01/31
#=======================
use warnings;
use v5.10;
use utf8;

# circumference circle user input

print "enter radius: ";
chomp($radius = <STDIN>);

$pi = 3.141592654;
$circumference = 2 * $pi * $radius;

say "circumference is: $circumference";

