#!/usr/bin/perl
#=======================
# Author : Ali Moradzade
# Created: 2022/01/31
#=======================
use warnings;
use v5.10;
use utf8;

# calculate circuferemence of a circle from its radius
$pi = 3.141592654;
$radius = 12.5;

$circuferemence = 2 * $pi * $radius;
say "circuferemence is $circuferemence";

