#!/bin/perl
#=======================
# Author : Ali Moradzade
# Created: 2022/01/31
#=======================
use warnings;
use v5.10;
use utf8;

# output with print

print "hello world\n";

print "the answer is ";
print 6 * 7;
print ".\n";

print "The answer is ", 6 * 7, ".\n";

say "The answer is ", 6 * 7, '.';
