#!/bin/perl
#=======================
# Author : Ali Moradzade
# Created: 2022/01/31
#=======================
use warnings;
use v5.10;
use utf8;

# reading input

$line = <STDIN>;
if ($line eq "\n") {
	say "That was just a blank line!";
}
else {
	print "That line of input was: $line";
}
