#!/bin/perl
#=======================
# Author : Ali Moradzade
# Created: 2022/01/31
#=======================
use warnings;
use v5.10;
use utf8;

# defined function

$next_line = <STDIN>;
if (defined($next_line)) {
	print "The input was $next_line";
}
else {
	say "No input available!";
}
