#!/bin/perl
#=======================
# Author : Ali Moradzade
# Created: 2022/01/31
#=======================
use warnings;
use v5.10;
use utf8;

# chomp operator

$text = "a line of text\n";
chomp($text);

print "This is text: $text.\n";
