#!/bin/perl
#=======================
# Author : Ali Moradzade
# Created: 2022/01/31
#=======================

# double quote

print "barney\n";
print "hello world\n";

print "The last character of this string is a quote mark:\"\n";

print "coke\tsprite\n";

# print "\x{2668}"; # does not work! (but in book it works)
# print "\N{SNOWMAN}"; # does not work! (but in book it works)

