#!/usr/bin/perl
#=======================
# Author : Ali Moradzade
# Created: 2022/02/02
#=======================
use warnings;
use v5.10;
use utf8;

# persistant private variables

sub marine {
	state $n = 0;
	$n += 1;
	say "Hello, sailor number $n!";
}

sub running_sum {
	state $sum = 0;
	state @numbers;

	foreach my $number (@_) {
		push @numbers, $number;
		$sum += $number;
	}

	say "The sum of (@numbers) is $sum";
}

&marine;
&marine;
&marine;

running_sum(5, 6);
running_sum(1..3);
running_sum(4);
