#!/usr/bin/perl
#=======================
# Author : Ali Moradzade
# Created: 2022/02/01
#=======================
use warnings;
use v5.10;
use utf8;

# variable length parameter lists

sub max {
	my($max_so_far) = shift @_;
	foreach (@_) {
		if ($_ > $max_so_far) {
			$max_so_far = $_;
		}
	}
	$max_so_far;
}

say &max(1, 2, 3);
say &max(1, 10);
say &max(1, 10, 20, 35, 99);
