#!/usr/bin/perl
#=======================
# Author : Ali Moradzade
# Created: 2022/02/01
#=======================
use warnings;
use v5.10;
use utf8;

# private variables in subroutines

sub max {
	my($m, $n);
	($m, $n) = @_;
	# or simply my($m, $n) = @_

	if ($m > $n) {$m} else {$n}
}

say &max(30, 40);
