#!/usr/bin/perl
#=======================
# Author : Ali Moradzade
# Created: 2022/02/03
#=======================
use warnings;
use v5.10;
use utf8;
use autodie;

#ex7 03 period

while (<>) {
	chomp;
	if (/\./) {
		say;
	}
}
