#!/usr/bin/perl
#=======================
# Author : Ali Moradzade
# Created: 2022/02/04
#=======================
use warnings;
use v5.10;
use utf8;
use autodie;

#ex9 01 three consecutive

my $what = 'fred|barney';

while (<>) {
	if (/($what){3}/) {
		say "\tMatched!";
	} else {
		say "\tNo match!";
	}
}
