#!/usr/bin/perl
#=======================
# Author : Ali Moradzade
# Created: 2022/02/02
#=======================
use warnings;
use v5.10;
use utf8;

#ex4 02 sum 1 to 1000

sub sum {
	my $sum = 0;
	foreach (@_) {
		$sum += $_;
	}
	return $sum;
}

say "The numbers from 1 to 1000 add up to ", &sum(1..1000), ".";
