#!/usr/bin/perl
#=======================
# Author : Ali Moradzade
# Created: 2022/02/02
#=======================
use warnings;
use v5.10;
use utf8;

#ex4 02 sum 1 to 1000

sub sum_1_to_1000 {
	my $sum = 0;
	foreach (1..1000) {
		$sum += $_;
	}
	return $sum;
}

$result = &sum_1_to_1000;
say "The result is $result.";
