#!/usr/bin/perl
#=======================
# Author : Ali Moradzade
# Created: 2022/02/04
#=======================
use warnings;
use v5.10;
use utf8;
use autodie;

use File::Basename;

#script 01 basename

my $name = "/usr/local/bin/perl";
my $basename = basename($name);
my $dirname = dirname($name);

say "$name ==> $dirname -- $basename";
