#!/usr/bin/perl
#=======================
# Author : Ali Moradzade
# Created: 2022/02/03
#=======================
use warnings;
use v5.10;
use utf8;
use autodie;

# non greedy qunatifiers

my $text = '<b>Fred</b> and <b>Barney</b>';
say "$text";

$text =~ s#<b>(.*)</b>#<b>\U$1\E</b>#g;
say "$text";
say "";

$text = '<b>Fred</b> and <b>Barney</b>';
say "$text";

$text =~ s#<b>(.*?)</b>#<b>\U$1\E</b>#g;
say "$text";
