#!/usr/bin/perl
#=======================
# Author : Ali Moradzade
# Created: 2022/02/02
#=======================
use warnings;
use v5.10;
use utf8;

# diamond operator

while (defined($line = <>)) {
	chomp($line);
	say "It was $line that I saw!";
}
