#!/usr/bin/perl
#=======================
# Author : Ali Moradzade
# Created: 2022/02/02
#=======================
use warnings;
use v5.10;
use utf8;

# printf

$user = "ali";
$days_to_die = 100;

printf "Hello, %s; your password expires in %d days!\n",
	$user, $days_to_die;

printf "%g %g %g\n", 5/2, 51/17, 51 ** 17;

printf "in %d days!\n", 17.85;

printf "in 0x%x days!\n", 17; # in Ox11 days!
printf "in 0%o days!\n", 17; # in 021 days!

printf "%6d\n", 42;
printf "%2d\n", 2e3 + 1.95;

printf "%10s\n", "wilma";

printf "%12f\n", 6 * 7 + 2/3;
printf "%12.3f\n", 6 * 7 + 2/3;
printf "%12.0f\n", 6 * 7 + 2/3;

printf "Monthly interest rate: %.2f%%\n",
	5.25/12;

printf "%*s\n", 20, "wilma";

printf "%*.*f\n", 6, 2, 3.1415926;
printf "%*.*f\n", 6, 3, 3.1415926;
