#!/usr/bin/perl
#=======================
# Author : Ali Moradzade
# Created: 2022/02/02
#=======================
use warnings;
use v5.10;
use utf8;

#ex4 01 total

sub total {
	my $sum = 0;
	foreach (@_) {
		$sum += $_;
	}
	return $sum;
}

my @fred = qw{ 1 3 5 7 9 };
my $fred_total = total(@fred);

say "The total of \@fred is $fred_total.";
say "Enter some numbers on separate lines:";
my $user_total = total(<STDIN>);

print "The total of those numbers is $user_total.\n";
