#!/usr/bin/perl
#=======================
# Author : Ali Moradzade
# Created: 2022/02/01
#=======================
use warnings;
use v5.10;
use utf8;

#ex3 03 2 sorting strings

chomp(@lines = <STDIN>);
@sorted = sort @lines;
print "@sorted\n";

print sort <STDIN>;
