#!/usr/bin/perl
#=======================
# Author : Ali Moradzade
# Created: 2022/02/01
#=======================
use warnings;
use v5.10;
use utf8;

#ex3 03 sorting strings

say "Enter list of strings on each line, then press ctrl-d:";
@lines = <STDIN>;

@sorted = sort(@lines);

say "\nEach on on its own line:";
say @sorted;

say "All of them in one line:";
chomp(@sorted);
say "@sorted";
