#!/usr/bin/perl
#=======================
# Author : Ali Moradzade
# Created: 2022/02/02
#=======================
use warnings;
use v5.10;
use utf8;
use autodie;

# filehandles in a scalar

open my $rocks_fh, '>', 'rocks.txt';

$_ = "Hello World!";

say {$rocks_fh} $_;
