#!/usr/bin/perl
#=======================
# Author : Ali Moradzade
# Created: 2022/02/02
#=======================
use warnings;
use v5.10;
use utf8;
use autodie;

# using filehandles

open PASSWD, '<', '/etc/passwd';

while (<PASSWD>) {
	print;
}

open LOG, '>', 'logfile';
print LOG "Captain's log, stardate 3.14159\n";
