#!/bin/perl
#=======================
# Author : Ali Moradzade
# Created: 2022/01/31
#=======================

# bad hello world

	print # This is a comment
"Hello, world!\n"
; # Don't write your Perl code like this!
