#!/usr/bin/perl
#=======================
# Author : Ali Moradzade
# Created: 2022/02/03
#=======================
use warnings;
use v5.10;
use utf8;
use autodie;

#scrip03 binding operator

my $some_other = "I dream of betty rubble.";
if ($some_other =~ /\brub/) {
	say "Aye, there's the rub.";
}

print "Do you like Perl? ";
my $like_perl = (<STDIN> =~ /\byes\b/i);

if ($like_perl) {
	say "You said earlier that you like Perl, so ...";
}
