#!/bin/perl
#=======================
# Author : Ali Moradzade
# Created: 2022/01/31
#=======================
use warnings;
use v5.10;
use utf8;

# while statement

$count = 0;
while ($count  < 10) {
	$count += 2;
	say "count is now $count";
}
