#!/bin/perl
#=======================
# Author : Ali Moradzade
# Created: 2022/01/31
#=======================
use warnings;
use v5.10;
use utf8;

# comparison operators

say 35 != 30 + 5;
say 35 == 30 + 5;
say '35' eq '35.0';
say 'fred' lt 'barney';
say 'fred' lt 'free';
say 'fred' eq "fred";
say 'fred' eq 'Fred';
say ' ' gt '';
