#!/bin/perl
#=======================
# Author : Ali Moradzade
# Created: 2022/01/31
#=======================
use warnings;
use v5.10;
use utf8;

# using undef

# add up some odd numbers
$n = 1;
while ($n < 10) {
	say "$n";
	$sum += $n;

	$n += 2;
}

say "sum is: $sum";
