#!/bin/perl
#=======================
# Author : Ali Moradzade
# Created: 2022/01/31
#=======================

# strings

print 'fred';
print 'barney';
print '';
print 'Don\' let an apostrophe end this string prematurely!';
print '\'\\'; # sing quote followed by backslash

print 'hello
there';

print 'hello\nthere' # hello\nthere
