#!/bin/perl
#=======================
# Author : Ali Moradzade
# Created: 2022/01/31
#=======================
use warnings;
use v5.10;
use utf8;

# else statment

$name = 'fred';
if ($name gt 'fred')
{
	print "'$name' comes after 'fred' in sorted order.\n";
}
else 
{
	print "'$name' does not come after 'fred'.\n";
	print "Maybe it's the same string, in fact.\n";
}
