#!/usr/bin/perl
#=======================
# Author : Ali Moradzade
# Created: 2022/02/04
#=======================
use warnings;
use v5.10;
use utf8;
use autodie;

#ex10 03 environment variables

$ENV{ZERO} = 0;
$ENV{EMPTY} = '';
$ENV{UNDEFINED} = undef;

my $longest = 0;
foreach my $key (keys %ENV) {
	my $key_length = length($key);
	$longest = $key_length if $key_length > $longest;
}

foreach my $key (sort keys %ENV) {
	printf "%-${longest}s %s\n", $key, $ENV{$key} // "(undifened value)";
}
