#!/usr/bin/perl
#=======================
# Author : Ali Moradzade
# Created: 2022/02/01
#=======================
use warnings;
use v5.10;
use utf8;

#ex3 01 2 reverse list input
say "Enter some lines, then press Ctrl-D:";
print reverse <STDIN>;

