#!/usr/bin/perl
#=======================
# Author : Ali Moradzade
# Created: 2022/02/01
#=======================
use warnings;
use v5.10;
use utf8;

# stdin in list context

@lines = <STDIN>;
say "@lines";

chomp(@lines = <STDIN>);
say "@lines";
