#!/usr/bin/perl
#=======================
# Author : Ali Moradzade
# Created: 2022/02/01
#=======================
use warnings;
use v5.10;
use utf8;

# push pop

@array = 5..9;
say @array;

$fred = pop(@array);
say @array;
say $fred;

$barney = pop @array;
say @array;
say $barney;

push(@array, 0);
say @array;

push(@array, 8);
say @array;

push(@array, 1..10);
say @array;

@others = qw/ 9 0 2 1 0/;
push(@array, @others);
say @array;
