#!/usr/bin/perl
#=======================
# Author : Ali Moradzade
# Created: 2022/02/01
#=======================
use warnings;
use v5.10;
use utf8;

# list literals

say (1, 2, 3);
say (1, 2, 3,);
say ("fred", 4.5);
say (1..10);

say (0, 2..6, 10, 12);

say (5..1); # wont work

$low = 1;
$high = 5;

say ($low .. $high);
say ($low + 1 .. $high - 1);
