#!/usr/bin/perl
#=======================
# Author : Ali Moradzade
# Created: 2022/02/01
#=======================
use warnings;
use v5.10;
use utf8;

# splice operator

@array = qw( pebbles dino fred barney betty );
say @array;

@removed = splice(@array, 2);
say @array;
say @removed;
say "";

@array = qw/pebbles dino fred barney betty/;
say @array;
@removed = splice(@array, 1, 2);
say @array;
say @removed;
say "";

@array = 1..8;
say @array;
splice(@array, 1, 0, qw/first second third/);
say @array;
