#!/usr/bin/perl
#=======================
# Author : Ali Moradzade
# Created: 2022/02/01
#=======================
use warnings;
use v5.10;
use utf8;

# forcing scalary context

@rocks = qw(talc quartz jade obsidian);

say "How many rocks do you have?";

say "I have ", @rocks, " rocks!";
say "I have ", scalar(@rocks), " rocks!";
