#!/usr/bin/perl
#=======================
# Author : Ali Moradzade
# Created: 2022/02/01
#=======================
use warnings;
use v5.10;
use utf8;

# default variable

foreach (1..10) {
	say "I can count to $_!";
}

$_ = "Yabba dabba doo\n";
say;
